// packages/adherev-ui-contextmenu/src/ContextMenu.tsx
import { computed, createApp, defineComponent, onMounted, provide, reactive, ref } from 'vue';
import { array, object } from 'vue-types';

import Menu from './Menu';
import { IComponent, IConfig, IData } from './types';

const selectorPrefix = 'adherev-ui-contextmenu';

export type ContextReturnType = {
  config: IConfig;
  el: HTMLElement;
};

const props = {
  data: array<IData>().def([]),
  config: object<IConfig>().def(),
  el: object<HTMLElement>().def(),
};

/**
 * ContextMenuComponent
 * @class ContextMenuComponent
 * @classdesc ContextMenuComponent
 */
const ContextMenuComponent = defineComponent({
  props,
  setup(props, { expose }) {
    const menuIns = ref<any>(null);

    const context = reactive({
      config: props.config,
      el: props.el,
    });

    const getStyle = computed(() => ({
      zIndex: 9999 * 2,
    }));

    onMounted(() => mount());

    const onClick = (e: MouseEvent) => {
      e.stopPropagation();

      props.el?.parentElement?.removeChild?.(props.el);
    };

    const onContextMenu = (e: MouseEvent) => {
      e.preventDefault();

      props.el?.parentElement?.removeChild?.(props.el);
    };

    const mount = () => menuIns.value.mount();

    provide('context', context);

    expose({
      mount,
    });

    return () => (
      <div
        class={selectorPrefix}
        style={getStyle.value}
        onClick={onClick}
        onContextmenu={onContextMenu}
      >
        <Menu
          data={props.data}
          className={props.config.className}
          style={props.config.style}
          ref={menuIns}
        />
      </div>
    );
  },
});

const ContextMenu: IComponent = {
  /**
   * config
   * {
   *   name - {String} 名字
   *   icon - {String} 图标
   *   id - {String} 唯一的id
   *   disabled - {Boolean} 不可用
   *   separation - {Bolean} 分割线
   *   attribute - {Object} 自定义属性
   *   children - {Array<Object> 孩子
   * }
   *{
   *   width - {Number} 宽度
   *   x - {Number} 显示的x坐标 相对于body
   *   y - {Number} 现实的y坐标 相对于body
   *   maskClosable - {Boolean} 点击其他位置是否关闭菜单
   *   handler - {Function} 点击的事件句柄
   * }
   * @return {HTMLDivElement}
   * @param data
   * @param defaultConfig
   */
  open(data: IData[], defaultConfig: IConfig) {
    const config: IConfig = { ...defaultConfig, width: 200, maskClosable: true };

    const parentEl = document.createElement('div');

    document.body.appendChild(parentEl);

    const app = createApp({
      setup() {
        const root = ref<any>(null);

        onMounted(() => {
          root.value.mount();
        });

        provide('root', {
          unmount() {
            try {
              // @ts-ignore
              app.unmount();
            } catch (err) {
              (parentEl as HTMLElement)?.parentElement?.removeChild(parentEl);
            }
          },
        });

        return () => <ContextMenuComponent ref={root} data={data} config={config} el={parentEl} />;
      },
    }).mount(parentEl);

    return {
      vm: app,
      el: parentEl,
    };
  },
  /**
   * close
   * @param vm
   * @param el
   */
  close({ vm, el }) {
    try {
      vm.unmount();
    } catch (err) {
      (el as HTMLElement)?.parentElement?.removeChild(el);
    }
  },
};

export default ContextMenu;

// packages/adherev-ui-contextmenu/lib/ContextMenu.jsx
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var vue_1 = require("vue");
var vue_types_1 = require("vue-types");
var Menu_1 = (0, tslib_1.__importDefault)(require("./Menu"));
var selectorPrefix = 'adherev-ui-contextmenu';
var props = {
    data: (0, vue_types_1.array)().def([]),
    config: (0, vue_types_1.object)().def(),
    el: (0, vue_types_1.object)().def(),
};
/**
 * ContextMenuComponent
 * @class ContextMenuComponent
 * @classdesc ContextMenuComponent
 */
var ContextMenuComponent = (0, vue_1.defineComponent)({
    props: props,
    setup: function (props, _a) {
        var expose = _a.expose;
        var menuIns = (0, vue_1.ref)(null);
        var context = (0, vue_1.reactive)({
            config: props.config,
            el: props.el,
        });
        var getStyle = (0, vue_1.computed)(function () { return ({
            zIndex: 9999 * 2,
        }); });
        (0, vue_1.onMounted)(function () { return mount(); });
        var onClick = function (e) {
            var _a, _b, _c;
            e.stopPropagation();
            (_c = (_b = (_a = props.el) === null || _a === void 0 ? void 0 : _a.parentElement) === null || _b === void 0 ? void 0 : _b.removeChild) === null || _c === void 0 ? void 0 : _c.call(_b, props.el);
        };
        var onContextMenu = function (e) {
            var _a, _b, _c;
            e.preventDefault();
            (_c = (_b = (_a = props.el) === null || _a === void 0 ? void 0 : _a.parentElement) === null || _b === void 0 ? void 0 : _b.removeChild) === null || _c === void 0 ? void 0 : _c.call(_b, props.el);
        };
        var mount = function () { return menuIns.value.mount(); };
        (0, vue_1.provide)('context', context);
        expose({
            mount: mount,
        });
        return function () { return (<div class={selectorPrefix} style={getStyle.value} 
        // @ts-ignore
        onClick={onClick} 
        // @ts-ignore
        onContextMenu={onContextMenu}>
        {/*@ts-ignore*/}
        <Menu_1.default data={props.data} className={props.config.className} style={props.config.style} ref={menuIns}/>
      </div>); };
    },
});
var ContextMenu = {
    /**
     * config
     * {
     *   name - {String} 名字
     *   icon - {String} 图标
     *   id - {String} 唯一的id
     *   disabled - {Boolean} 不可用
     *   separation - {Bolean} 分割线
     *   attribute - {Object} 自定义属性
     *   children - {Array<Object> 孩子
     * }
     *{
     *   width - {Number} 宽度
     *   x - {Number} 显示的x坐标 相对于body
     *   y - {Number} 现实的y坐标 相对于body
     *   maskClosable - {Boolean} 点击其他位置是否关闭菜单
     *   handler - {Function} 点击的事件句柄
     * }
     * @return {HTMLDivElement}
     * @param data
     * @param defaultConfig
     */
    open: function (data, defaultConfig) {
        var config = (0, tslib_1.__assign)((0, tslib_1.__assign)({}, defaultConfig), { width: 200, maskClosable: true });
        var parentEl = document.createElement('div');
        document.body.appendChild(parentEl);
        var app = (0, vue_1.createApp)({
            setup: function () {
                var root = (0, vue_1.ref)(null);
                (0, vue_1.onMounted)(function () {
                    root.value.mount();
                });
                (0, vue_1.provide)('root', {
                    unmount: function () {
                        var _a, _b;
                        console.log('app', app, parentEl);
                        try {
                            // @ts-ignore
                            app.unmount();
                        }
                        catch (err) {
                            (_b = (_a = parentEl) === null || _a === void 0 ? void 0 : _a.parentElement) === null || _b === void 0 ? void 0 : _b.removeChild(parentEl);
                        }
                    },
                });
                // @ts-ignore
                return function () { return <ContextMenuComponent ref={root} data={data} config={config} el={parentEl}/>; };
            },
        }).mount(parentEl);
        return {
            vm: app,
            el: parentEl,
        };
    },
    /**
     * close
     * @param vm
     * @param el
     */
    close: function (_a) {
        var _b, _c;
        var vm = _a.vm, el = _a.el;
        try {
            vm.unmount();
        }
        catch (err) {
            (_c = (_b = el) === null || _b === void 0 ? void 0 : _b.parentElement) === null || _c === void 0 ? void 0 : _c.removeChild(el);
        }
    },
};
exports.default = ContextMenu;
//# sourceMappingURL=ContextMenu.jsx.map
